# Generated by Django 4.0 on 2022-01-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompelted',
            new_name='datecompleted',
        ),
    ]
